FINNHUB_API_KEY = "ck76m4hr01qmp9pdbd1gck76m4hr01qmp9pdbd20"
POLYGON_API_KEY = "27tkT_VuoQb9Y25KuiTmzb3p3pXOL755"
AWS_ACCESS_KEY_ID = "AKIARBS75YKKQAX4Z55N"
AWS_SECRET_ACCESS_KEY = "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"
DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1163710431001595925/NQeCVcKpHqUphR4lk1Tm37w9PIrIl70U9I5V_D9ndY5y-iYZM9qpSUjn8im76dA6etvJ"
